version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true
    depends_on:
      - backend

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - '5174:5174'
    env_file:
      - ./dashboard/.env
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  pgdata: